<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><IsPackable>false</IsPackable></PropertyGroup>
  <Import Project="../../Platonic.props" />
  <ItemGroup><ProjectReference Include="../Ara3D.BimOpenSchema.BuildingModel.Workflows/Ara3D.BimOpenSchema.BuildingModel.Workflows.csproj" /></ItemGroup>
</Project>
