<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <Import Project="../../Platonic.props" />
  <ItemGroup>
    <ProjectReference Include="../Ara3D.BimOpenSchema.DataModel/Ara3D.BimOpenSchema.DataModel.csproj" />
    <PackageReference Include="Parquet.Net" Version="$(Ara3DParquetNetVersion)" />
    <PackageReference Include="DuckDB.NET.Data.Full" Version="$(Ara3DDuckDbNetDataFullVersion)" />
  </ItemGroup>
</Project>
