<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ara3D.DataTable" Version="$(Ara3DSdkVersion)" />
    <PackageReference Include="Ara3D.Geometry" Version="$(Ara3DSdkVersion)" />
    <PackageReference Include="Ara3D.Models" Version="$(Ara3DSdkVersion)" />
  </ItemGroup>

</Project>
