<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Ara3D.BimOpenSchema.IO</PackageId>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ara3D.Logging" Version="$(Ara3DSdkVersion)" />
    <PackageReference Include="ClosedXML" Version="$(Ara3DClosedXmlVersion)" />
    <PackageReference Include="DuckDB.NET.Data.Full" Version="$(Ara3DDuckDbNetDataFullVersion)" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="$(Ara3DMicrosoftDataSqliteVersion)" />
    <PackageReference Include="Parquet.Net" Version="$(Ara3DParquetNetVersion)" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Link="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ara3D.BimOpenSchema\Ara3D.BimOpenSchema.csproj" />
  </ItemGroup>

</Project>
